INSERT INTO ingredients (title) VALUES ('Vodka');
INSERT INTO ingredients (title) VALUES ('Gin');
INSERT INTO ingredients (title) VALUES ('White Rum');
INSERT INTO ingredients (title) VALUES ('Dark Rum');
INSERT INTO ingredients (title) VALUES ('Tequila');
INSERT INTO ingredients (title) VALUES ('Absinthe');
INSERT INTO ingredients (title) VALUES ('Brandy');
INSERT INTO ingredients (title) VALUES ('Bourbon Whiskey');
INSERT INTO ingredients (title) VALUES ('Irish Whiskey');
INSERT INTO ingredients (title) VALUES ('Scotch Whiskey');
INSERT INTO ingredients (title) VALUES ('Champagne');
INSERT INTO ingredients (title) VALUES ('White wine');
INSERT INTO ingredients (title) VALUES ('Red wine');
INSERT INTO ingredients (title) VALUES ('Beer');
INSERT INTO ingredients (title) VALUES ('Sweet vermouth');
INSERT INTO ingredients (title) VALUES ('Dry vermouth');
INSERT INTO ingredients (title) VALUES ('Triple sec liqueur');
INSERT INTO ingredients (title) VALUES ('Grand Marnier liqueur');
INSERT INTO ingredients (title) VALUES ('Maraschino liqueur');
INSERT INTO ingredients (title) VALUES ('Apricot brandy liqueur');
INSERT INTO ingredients (title) VALUES ('Coffee liqueur');
INSERT INTO ingredients (title) VALUES ('Amaretto liqueur');
INSERT INTO ingredients (title) VALUES ('White crème de cacao liqueur');
INSERT INTO ingredients (title) VALUES ('Dark crème de cacao liqueur');
INSERT INTO ingredients (title) VALUES ('Black rasberry liqueur');
INSERT INTO ingredients (title) VALUES ('Coconut liqueur');
INSERT INTO ingredients (title) VALUES ('Peach Schnapps liqueur');
INSERT INTO ingredients (title) VALUES ('Crème de banane liqueur');
INSERT INTO ingredients (title) VALUES ('Southern Comport liqueur');
INSERT INTO ingredients (title) VALUES ('Angoustura Aromatic Bitters');
INSERT INTO ingredients (title) VALUES ('Orange bitters');
INSERT INTO ingredients (title) VALUES ('Campari bitter');
INSERT INTO ingredients (title) VALUES ('Simple syrup');
INSERT INTO ingredients (title) VALUES ('Grenadine');
INSERT INTO ingredients (title) VALUES ('Lime wheel');
INSERT INTO ingredients (title) VALUES ('Black pepper');
INSERT INTO ingredients (title) VALUES ('Ice');
INSERT INTO ingredients (title) VALUES ('Basil Leaves');
INSERT INTO ingredients (title) VALUES ('Egg white');
INSERT INTO ingredients (title) VALUES ('Mint Leaves');
INSERT INTO ingredients (title) VALUES ('Agave syrup');
INSERT INTO ingredients (title) VALUES ('Black Coffee');
INSERT INTO ingredients (title) VALUES ('Cream');
INSERT INTO ingredients (title) VALUES ('Milk');
INSERT INTO ingredients (title) VALUES ('Brown Sugar');
INSERT INTO ingredients (title) VALUES ('Fresh lime juice');
INSERT INTO ingredients (title) VALUES ('Lemon juice');
INSERT INTO ingredients (title) VALUES ('Apple juice');
INSERT INTO ingredients (title) VALUES ('Orange juice');
INSERT INTO ingredients (title) VALUES ('Pinapple juice');
INSERT INTO ingredients (title) VALUES ('Cranberry juice');
INSERT INTO ingredients (title) VALUES ('Grapefruit juice');
INSERT INTO ingredients (title) VALUES ('Soda');
INSERT INTO ingredients (title) VALUES ('Ginger ale');
INSERT INTO ingredients (title) VALUES ('Ginger beer');
INSERT INTO ingredients (title) VALUES ('Fanta');
INSERT INTO ingredients (title) VALUES ('Appelsín');
INSERT INTO ingredients (title) VALUES ('Sprite');
INSERT INTO ingredients (title) VALUES ('Coca Cola');
INSERT INTO ingredients (title) VALUES ('Pepsi');
INSERT INTO ingredients (title) VALUES ('Tonic water');
INSERT INTO ingredients (title) VALUES ('Lemonade');
INSERT INTO ingredients (title) VALUES ('Apple slice');
INSERT INTO ingredients (title) VALUES ('Rasberries');
INSERT INTO ingredients (title) VALUES ('Blueberries');
INSERT INTO ingredients (title) VALUES ('Passion fruit');
INSERT INTO ingredients (title) VALUES ('Watermelon');
INSERT INTO ingredients (title) VALUES ('Strawberries');
INSERT INTO ingredients (title) VALUES ('Ginger');
INSERT INTO ingredients (title) VALUES ('Cucumber');

